### ISSUE TITLE
API proposal

### ISSUE THREAD

**Issue by felixgirault** [mattjmattj/win-ze-yes.js#1]
- Positive assertion: `needsZeYesToWin()`
- Negative assertion: `needsZeNoToWin()`

**Comment by felixgirault** [comment]
Or even better:

``` js
var foo = 12;

win(foo).ze.yes();
win(foo).ze.yes.needs.ze.no();
win(foo).ze.yes.needs.ze.no.to.win.against.the.no();
```

If it ends with `yes()`, it is a positive assertion, if it ends with `no()`, a negative one.

**Comment by felixgirault** [comment]
For clarity, it would also be cool to support alternative words:

``` js
win(foo).the.yes.needs.the.no();
win(foo).ze.yaisse.nidze.zeu.nau();
win(foo).zeu.yaisse.tou.wine.eugaïnste.zeu.nau();
```

**Comment by mattjmattj** [comment]
Please see pull request #2
